document.write('<script type="text/javascript">if(!window.qxsettings)qxsettings={};\
if(qxsettings["qx.resourceUri"]==undefined)qxsettings["qx.resourceUri"]="../qooxdoolink/frontend/framework/source/resource";\
if(qxsettings["Smokeping.resourceUri"]==undefined)qxsettings["Smokeping.resourceUri"]="./resource";\
if(qxsettings["qx.theme"]==undefined)qxsettings["qx.theme"]="qx.theme.ClassicRoyale";\
if(qxsettings["qx.iconTheme"]==undefined)qxsettings["qx.iconTheme"]="qx.theme.icon.CrystalClear";\
if(qxsettings["qx.minLogLevel"]==undefined)qxsettings["qx.minLogLevel"]=200;\
if(qxsettings["qx.logAppender"]==undefined)qxsettings["qx.logAppender"]="qx.log.appender.Native";\
if(qxsettings["qx.application"]==undefined)qxsettings["qx.application"]="Smokeping.Application";\
if(qxsettings["qx.version"]==undefined)qxsettings["qx.version"]="0.7.2 ";\
if(qxsettings["qx.isSource"]==undefined)qxsettings["qx.isSource"]=true;\
if(!window.qxvariants)qxvariants={};\
</script><script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/core/Bootstrap.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/lang/Core.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/lang/Generics.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/core/Log.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/core/Setting.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/lang/Array.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/core/Variant.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/core/Client.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/lang/Object.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/core/Aspect.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/Class.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/Mixin.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/Interface.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/locale/MTranslation.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/log/MLogging.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/core/MUserData.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/core/LegacyProperty.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/core/Property.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/lang/String.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/core/Object.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/core/Target.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/event/type/Event.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/event/type/DataEvent.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/event/type/ChangeEvent.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/log/Filter.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/log/DefaultFilter.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/log/LogEventProcessor.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/log/appender/Abstract.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/log/appender/Window.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/log/appender/FireBug.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/log/appender/Native.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/log/Logger.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/dev/StackTrace.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/lang/Function.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/html/String.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/dom/String.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/html/Entity.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/html/EventRegistration.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/core/Init.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/application/IApplication.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/core/Version.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/OO.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/Theme.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/classic/color/Royale.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/classic/Border.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/classic/font/Default.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/util/manager/Value.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/Alias.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/classic/Widget.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/classic/Appearance.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/icon/Nuvola.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/ClassicRoyale.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/icon/CrystalClear.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/application/Gui.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/core/Widget.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/html/Dimension.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/html/Style.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/html/StyleSheet.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/core/Parent.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/event/type/FocusEvent.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/event/handler/EventHandler.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/dom/Node.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/event/handler/KeyEventHandler.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/event/type/DomEvent.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/event/type/KeyEvent.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/event/type/MouseEvent.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/bom/Viewport.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/util/manager/Object.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/embed/IframeManager.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/layout/CanvasLayout.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/layout/impl/LayoutImpl.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/lang/Number.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/layout/impl/CanvasLayoutImpl.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/core/ClientDocument.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/basic/Terminator.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/core/ClientDocumentBlocker.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/manager/Appearance.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/manager/Meta.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/manager/Color.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/util/ColorUtil.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/manager/Border.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/core/Border.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/manager/Font.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/core/Font.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/manager/Icon.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/theme/manager/Widget.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/event/handler/FocusHandler.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/html/Location.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/html/Scroll.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/image/Manager.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/html/Offset.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/html/ScrollIntoView.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/client/Timer.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/image/PreloaderSystem.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/image/PreloaderManager.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/image/Preloader.js"></script>\
<script type="text/javascript" src="./class/Smokeping/Application.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/remote/Rpc.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/net/Http.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/util/Mime.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/remote/Request.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/remote/RequestQueue.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/remote/Exchange.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/remote/Response.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/remote/AbstractRemoteTransport.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/remote/XmlHttpTransport.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/net/HttpRequest.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/Json.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/remote/IframeTransport.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/html/Iframe.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/io/remote/ScriptTransport.js"></script>\
<script type="text/javascript" src="./class/Smokeping/io/Rpc.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/layout/BoxLayout.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/layout/impl/VerticalBoxLayoutImpl.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/util/Validation.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/layout/impl/HorizontalBoxLayoutImpl.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/layout/VerticalBoxLayout.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/basic/Atom.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/basic/Label.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/locale/Manager.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/locale/LocalizedString.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/dom/Element.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/basic/Image.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/splitpane/SplitPane.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/splitpane/SplitPaneSlider.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/splitpane/SplitPaneSplitter.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/splitpane/SplitPaneKnob.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/bom/element/Location.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/bom/element/Style.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/bom/element/Dimension.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/bom/Document.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/splitpane/HorizontalSplitPane.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/tree/AbstractTreeElement.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/tree/TreeRowStructure.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/embed/HtmlEmbed.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/tree/TreeFolder.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/tree/Tree.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/selection/SelectionManager.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/selection/Selection.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/tree/SelectionManager.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/tree/TreeFile.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/layout/HorizontalBoxLayout.js"></script>\
<script type="text/javascript" src="./class/Smokeping/ui/TargetTree.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/event/message/Bus.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/event/message/Message.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/layout/FlowLayout.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/layout/impl/FlowLayoutImpl.js"></script>\
<script type="text/javascript" src="./class/Smokeping/ui/Graphs.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/ui/form/Button.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/locale/Locale.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/locale/data/C.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/locale/data/en.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/locale/data/de.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/locale/data/fr.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/locale/translation/C.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/locale/translation/en.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/locale/translation/de.js"></script>\
<script type="text/javascript" src="../qooxdoolink/frontend/framework/source/class/qx/locale/translation/fr.js"></script>\
<script type="text/javascript" src="./class/Smokeping/translation/C.js"></script>\
<script type="text/javascript" src="./class/Smokeping/translation/en.js"></script>\
<script type="text/javascript" src="./class/Smokeping/translation/de.js"></script>\
<script type="text/javascript" src="./class/Smokeping/translation/fr.js"></script>\
');